FROM node:20-alpine

WORKDIR /app

# copy package files first
COPY package.json package-lock.json ./

# IMPORTANT: force rebuild optional deps
RUN npm ci --include=optional

# copy source
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]